---
- name: Create user if it doesn't exists
  user: name={{ user }} home={{ home }}

- name: Create upstart configuration
  template: src=upstart.conf.j2 dest=/etc/init/{{ application_name }}.conf

- name: Update code
  copy: src=projects/{{ application_name }}/ dest={{ home }}/{{ application_name }}

- name: Create log folder
  file: path=/var/log/{{ application_name }} owner={{ user }} group={{ user }} state=directory

- name: Installs gearman
  apt: pkg=gearman state=installed

- name: Installs vagrant
  apt: pkg=vagrant state=installed

- name: Checks for permission
  file: path={{ home }}/{{ application_name }} owner={{ user }} group={{ user }} recurse=yes

#- name: Start the service vagrant-worker
#  service: name={{ application_name }} state=restarted

- name: Installs vagrant-worker python requirements
  pip: requirements={{ home }}/{{ application_name }}/requirements.txt
